### ISSUE TITLE
Todo-list

### ISSUE THREAD

**Issue by Hanse** [webkom/nyitrondheim#13]
- [x] Smaller background image on mobile devices.
- [x] Make the union picker work on mobile devices.
- [ ] Improve the caching system.
- [x] Add an admin page for unions
- [x] Make union specific articles linkable /abakus/article-title 
- [x] Fix before/after on the upmost articles.
- [x] Merge the different admin pages into one for simplicity.
- [x] Pick the background randomly.
- [x] Add a bootstrapping script for the database.
- [x] Add the uploaded article images to articles.
- [x] Add a link to the calendar somewhere on the front page.
- [ ] Style the calendar. 
- [x] Hide non-school users from the union picker (admin/generelt etc.).
- [x] Make it possible to create articles for all unions from the general admin panel at /admin.
- [ ] Should probably log you out from the admin panel if you change vital information about your own user. 
- [x] Compress background images.
- [ ] Fix the progress bar in the admin panel.
